# Generated by Django 5.2.1 on 2026-01-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='identification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='professor_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد استادی'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره دانشجویی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_professor',
            field=models.BooleanField(default=False, verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='دانشجو'),
        ),
    ]
