# Generated by Django 6.0.1 on 2026-02-02 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_units', models.PositiveIntegerField(default=12, verbose_name='حداقل واحد')),
                ('max_units', models.PositiveIntegerField(default=20, verbose_name='حداکثر واحد')),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام درس')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد درس')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('day', models.CharField(choices=[('1', 'شنبه'), ('2', 'یکشنبه'), ('3', 'دوشنبه'), ('4', 'سه\u200cشنبه'), ('5', 'چهارشنبه'), ('6', 'پنج\u200cشنبه'), ('7', 'جمعه')], default='1', max_length=1, verbose_name='روز برگزاری')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('location', models.CharField(max_length=100, verbose_name='مکان برگزاری')),
                ('prerequisites', models.ManyToManyField(blank=True, to='courses.course', verbose_name='پیش\u200cنیازها')),
                ('professor', models.ForeignKey(limit_choices_to={'is_professor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
            },
        ),
    ]
