# Generated by Django 6.0.1 on 2026-02-02 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت\u200cنام')),
                ('is_passed', models.BooleanField(default=False, verbose_name='پاس شده')),
                ('term', models.CharField(default='1402-2', max_length=10, verbose_name='ترم')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='courses.course', verbose_name='درس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'انتخاب واحد',
                'verbose_name_plural': 'لیست انتخاب واحد',
                'unique_together': {('student', 'course', 'term')},
            },
        ),
    ]
