# Generated by Django 6.0 on 2025-12-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('shanbe', 'شنبه'), ('yekshanbe', 'یکشنبه'), ('doshanbe', 'دوشنبه'), ('seshanbe', 'سه\u200cشنبه'), ('chaharshanbe', 'چهارشنبه'), ('panjshanbe', 'پنج\u200cشنبه'), ('jome', 'جمعه')], max_length=20, verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان درس')),
                ('unique_code', models.CharField(max_length=20, unique=True, verbose_name='کد درس')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('time_slots', models.ManyToManyField(to='main.timeslot', verbose_name='زمان\u200cهای برگزاری')),
            ],
        ),
    ]
